### ISSUE TITLE
Issue a ser deletado

### ISSUE THREAD

**Issue by hellooliveira** [ud-portugues/POeTiSA#5]

**Comment by MagaliDuran** [comment]
Helô, veja se consegue deletar esse issue depois de replicar seu comentário no Issue da sentenças.

**Comment by hellooliveira** [comment]
Eu não consegui excluir :(

**Comment by MagaliDuran** [comment]
Todas as dúvidas de sentenças serão centralizadas no Issue aberto para isso.
