### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by GaybsGimenez** [ud-portugues/POeTiSA#6]
Oi, pessoal, tudo bem?

Me surgiu uma dúvida que na verdade não faz bem parte das POS tags... Vou tentar explicar. na frase: 
 -----------------------(amod->)
(170)  Há outras aparentes boas notícias em a pesquisa , ainda de acordo com Angélico .
 -------------------(NOUN)  (ADJ)  (NOUN) 

A parte acho que é sintática, tem uma relação de amod  indo de "aparentes" para "boas" , e, me parece que a relação deveria ser entre boas e notícias,(certo ?)

 Enfim, desculpa se  pergunta é meio boba ou fora da minha alçada, mas fiquei com isso na cabeça. (^^')

**Comment by gracanunes** [comment]
Entendo que não devemos nos preocupar com isso agora, pois essas relações dependem muito da etiquetação correta das POS tags. Então tudo pode mudar a partir de qualquer modificação das POS tags. Melhor nem olhar para isso agora.
