### ISSUE TITLE
Advérbios x Determinantes

### ISSUE THREAD

**Issue by claleni** [ud-portugues/POeTiSA#8]
A palavra "mais" normalmente é advérbio.
Mas em alguns casos ela pode ser pronomial indefinido, como em:
"O cenógrafo precisou de mais luz." e "Temos projeto para dar apoio em a integração de mais imigrantes"

Nesses casos, a palavra "mais" é anotada como determinante, certo?

(Obs.: Eu não estou conseguindo colocar label nas minhas issues gente, não aparece nada para mim.)

**Comment by gracanunes** [comment]
Na resposta a Helo, no issue das dúvidas sobre as sentenças do corpus, Magali comenta esse caso. Pode haver um ADV antes de NOUN, que é esse caso.

**Comment by claleni** [comment]
ok, obrigada
