### ISSUE TITLE
Usos diferentes de "que"

### ISSUE THREAD

**Issue by claleni** [ud-portugues/POeTiSA#9]
Na seguinte sentença:
"Que tanta história de suas vidas meninos e meninas ainda em flor teriam para contar?"

Esse "que" parece com "quantas" em: "Quantas tantas histórias eles têm para contar?"

Mas "que" pode ser advérbio?

**Comment by claleni** [comment]
Outro caso: "Como que a gente fica em casa?"

**Comment by MagaliDuran** [comment]
> Outro caso: "Como que a gente fica em casa?"

Clarissa, dê uma olhada no documento sobre ambiguidade do "QUE": https://docs.google.com/document/d/1a0WlGxQ05_4h5PnT4tQ78bhghJRUeFX5/edit

Em "Como que a gente fica em casa", pense em uma sentença análoga: Onde que você colocou os óculos? O "que", para mim, parece estar retomando o "onde", concorda?
